fix: clickhouse client permission error
Clickhouse client command was triggering a permission denied error:

$ tutor local run cairn-clickhouse cairn-client
Code: 586. DB::ErrnoException: Cannot create file:
//.clickhouse-client-history, errno: 13, strerror: Permission denied.
(CANNOT_CREATE_FILE)

Traceback (most recent call last):
  File "/scripts/cairn", line 161, in <module>
    main()
  File "/scripts/cairn", line 62, in main
    args.func(args)
  File "/scripts/cairn", line 68, in command_client
    subprocess.check_call(get_client_command())
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['clickhouse', 'client',
'--host', 'cairn-clickhouse', '--port', '9000', '--user', 'openedx',
'--password', 'xrIDmynTAiDuJeVZc5ar', '--multiline', '--multiquery',
'--database', 'openedx']' returned non-zero exit status 74.

This was because the home of the cairn client was set to "/".