fix: TypeError with problem-builder units
Problem builder units sometimes have subunits with None titles, which causes
the importcoursedata.py script to crash with the following traceback:

    Traceback (most recent call last):
      File "/openedx/scripts/importcoursedata.py", line 95, in <module>
        main()
      File "/openedx/scripts/importcoursedata.py", line 32, in main
        import_course(course.id)
      File "/openedx/scripts/importcoursedata.py", line 40, in import_course
        values = [
      File "/openedx/scripts/importcoursedata.py", line 41, in <listcomp>
        sql_format(
      File "/openedx/scripts/importcoursedata.py", line 78, in sql_format
        args = [sql_escape_string(arg).decode() for arg in args]
      File "/openedx/scripts/importcoursedata.py", line 78, in <listcomp>
        args = [sql_escape_string(arg).decode() for arg in args]
    TypeError: a bytes-like object is required, not 'NoneType'

See: https://openedx.slack.com/archives/DRW9ECU66/p1628935843000600